import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layout/NavBar";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <header className="bg-gray-600 p-2 my-2">Todo</header>
                <main className="flex p-4">
                    <ul>
                        <li>{children}</li>
                    </ul>
                </main>
                <footer className="bg-gray-600 p-2 my-2">@copy Dogyeom</footer>
            </body>
        </html>
    )
}
